export type Cat = { id: string; de: string; en: string; fr: string; it: string; rm: string; subs?: Cat[] };

export const CATS: Cat[] = [
  {
    id: "moebel",
    de: "Möbel",
    en: "Furniture",
    fr: "Meubles",
    it: "Mobili",
    rm: "Mobiglias",
    subs: [
      { id: "sofa", de: "Sofa", en: "Sofa", fr: "Canapé", it: "Divano", rm: "Sofa" },
      { id: "tisch", de: "Tisch", en: "Table", fr: "Table", it: "Tavolo", rm: "Maisa" },
      { id: "stuhl", de: "Stuhl", en: "Chair", fr: "Chaise", it: "Sedia", rm: "Sutga" },
      { id: "bett", de: "Bett", en: "Bed", fr: "Lit", it: "Letto", rm: "Letg" },
      { id: "schrank", de: "Schrank", en: "Cabinet", fr: "Armoire", it: "Armadio", rm: "Armadi" },
      { id: "regal", de: "Regal", en: "Shelf", fr: "Étagère", it: "Scaffale", rm: "Scaffal" },
      { id: "anderes-m", de: "Anderes", en: "Other", fr: "Autre", it: "Altro", rm: "Auter" },
    ],
  },
  {
    id: "haushalt",
    de: "Haushalt",
    en: "Household",
    fr: "Maison",
    it: "Casa",
    rm: "Chasa",
    subs: [
      { id: "lampe", de: "Lampe", en: "Lamp", fr: "Lampe", it: "Lampada", rm: "Lampa" },
      { id: "teppich", de: "Teppich", en: "Rug", fr: "Tapis", it: "Tappeto", rm: "Tapi" },
      { id: "deko", de: "Deko", en: "Decor", fr: "Déco", it: "Decor", rm: "Deco" },
      { id: "anderes-h", de: "Anderes", en: "Other", fr: "Autre", it: "Altro", rm: "Auter" },
    ],
  },
  {
    id: "kueche",
    de: "Küche",
    en: "Kitchen",
    fr: "Cuisine",
    it: "Cucina",
    rm: "Cuschina",
    subs: [
      { id: "geraet", de: "Gerät", en: "Appliance", fr: "Appareil", it: "Elettro", rm: "Apparat" },
      { id: "geschirr", de: "Geschirr", en: "Dishes", fr: "Vaisselle", it: "Stoviglie", rm: "Plaints" },
      { id: "anderes-k", de: "Anderes", en: "Other", fr: "Autre", it: "Altro", rm: "Auter" },
    ],
  },
  { id: "garten", de: "Garten", en: "Garden", fr: "Jardin", it: "Giardino", rm: "Garda" },
  { id: "kind", de: "Kind", en: "Kids", fr: "Enfant", it: "Bambini", rm: "Uffants" },
  { id: "mode", de: "Mode", en: "Clothes", fr: "Vêtements", it: "Abbigliamento", rm: "Vestgadira" },
  { id: "schuhe", de: "Schuhe", en: "Shoes", fr: "Chaussures", it: "Scarpe", rm: "Schalers" },
  { id: "sport", de: "Sport", en: "Sport", fr: "Sport", it: "Sport", rm: "Sport" },
  { id: "velo", de: "Velo", en: "Bike", fr: "Vélo", it: "Bici", rm: "Velo" },
  { id: "buecher", de: "Bücher", en: "Books", fr: "Livres", it: "Libri", rm: "Cudeschs" },
  { id: "medien", de: "Medien", en: "Media", fr: "Médias", it: "Media", rm: "Media" },
  { id: "elektronik", de: "Elektronik", en: "Electronics", fr: "Électronique", it: "Elettronica", rm: "Electronica" },
  { id: "handy", de: "Handy", en: "Phone", fr: "Téléphone", it: "Telefono", rm: "Telefon" },
  { id: "computer", de: "Computer", en: "Computer", fr: "Ordinateur", it: "Computer", rm: "Computer" },
  { id: "musik", de: "Musik", en: "Music", fr: "Musique", it: "Musica", rm: "Musica" },
  { id: "spiele", de: "Spiele", en: "Toys", fr: "Jeux", it: "Giochi", rm: "Gieus" },
  { id: "tiere", de: "Tiere", en: "Pets", fr: "Animaux", it: "Animali", rm: "Animals" },
  { id: "werkstatt", de: "Werkstatt", en: "Tools", fr: "Outils", it: "Attrezzi", rm: "Utensils" },
  { id: "buero", de: "Büro", en: "Office", fr: "Bureau", it: "Ufficio", rm: "Bureau" },
  { id: "anderes", de: "Anderes", en: "Other", fr: "Autre", it: "Altro", rm: "Auter" },
];
