export type Cat = { id: string; de: string; en: string; fr: string; it: string; subs?: Cat[] };

export const CATS: Cat[] = [
  {
    id: "moebel",
    de: "Möbel",
    en: "Furniture",
    fr: "Meubles",
    it: "Mobili",
    subs: [
      { id: "sofa", de: "Sofa", en: "Sofa", fr: "Canapé", it: "Divano" },
      { id: "tisch", de: "Tisch", en: "Table", fr: "Table", it: "Tavolo" },
      { id: "stuhl", de: "Stuhl", en: "Chair", fr: "Chaise", it: "Sedia" },
      { id: "bett", de: "Bett", en: "Bed", fr: "Lit", it: "Letto" },
      { id: "schrank", de: "Schrank", en: "Cabinet", fr: "Armoire", it: "Armadio" },
      { id: "regal", de: "Regal", en: "Shelf", fr: "Étagère", it: "Scaffale" },
      { id: "anderes-m", de: "Anderes", en: "Other", fr: "Autre", it: "Altro" },
    ],
  },
  {
    id: "haushalt",
    de: "Haushalt",
    en: "Household",
    fr: "Maison",
    it: "Casa",
    subs: [
      { id: "lampe", de: "Lampe", en: "Lamp", fr: "Lampe", it: "Lampada" },
      { id: "teppich", de: "Teppich", en: "Rug", fr: "Tapis", it: "Tappeto" },
      { id: "deko", de: "Deko", en: "Decor", fr: "Déco", it: "Decor" },
      { id: "anderes-h", de: "Anderes", en: "Other", fr: "Autre", it: "Altro" },
    ],
  },
  {
    id: "kueche",
    de: "Küche",
    en: "Kitchen",
    fr: "Cuisine",
    it: "Cucina",
    subs: [
      { id: "geraet", de: "Gerät", en: "Appliance", fr: "Appareil", it: "Elettro" },
      { id: "geschirr", de: "Geschirr", en: "Dishes", fr: "Vaisselle", it: "Stoviglie" },
      { id: "anderes-k", de: "Anderes", en: "Other", fr: "Autre", it: "Altro" },
    ],
  },
  { id: "garten", de: "Garten", en: "Garden", fr: "Jardin", it: "Giardino" },
  { id: "kind", de: "Kind", en: "Kids", fr: "Enfant", it: "Bambini" },
  { id: "mode", de: "Mode", en: "Clothes", fr: "Vêtements", it: "Abbigliamento" },
  { id: "schuhe", de: "Schuhe", en: "Shoes", fr: "Chaussures", it: "Scarpe" },
  { id: "sport", de: "Sport", en: "Sport", fr: "Sport", it: "Sport" },
  { id: "velo", de: "Velo", en: "Bike", fr: "Vélo", it: "Bici" },
  { id: "buecher", de: "Bücher", en: "Books", fr: "Livres", it: "Libri" },
  { id: "medien", de: "Medien", en: "Media", fr: "Médias", it: "Media" },
  { id: "elektronik", de: "Elektronik", en: "Electronics", fr: "Électronique", it: "Elettronica" },
  { id: "handy", de: "Handy", en: "Phone", fr: "Téléphone", it: "Telefono" },
  { id: "computer", de: "Computer", en: "Computer", fr: "Ordinateur", it: "Computer" },
  { id: "musik", de: "Musik", en: "Music", fr: "Musique", it: "Musica" },
  { id: "spiele", de: "Spiele", en: "Toys", fr: "Jeux", it: "Giochi" },
  { id: "tiere", de: "Tiere", en: "Pets", fr: "Animaux", it: "Animali" },
  { id: "werkstatt", de: "Werkstatt", en: "Tools", fr: "Outils", it: "Attrezzi" },
  { id: "buero", de: "Büro", en: "Office", fr: "Bureau", it: "Ufficio" },
  { id: "anderes", de: "Anderes", en: "Other", fr: "Autre", it: "Altro" },
];
